name: PR/main branch CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  make-tests:
    env:
      PACT_VERSION: ${{ github.sha }}
      PACT_BROKER_BASE_URL: ${{ vars.PACT_BROKER_BASE_URL }}
      PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
      - uses: replicatedhq/action-install-pact@v1
      - run: make test
      - if: github.event_name == 'push' || ( github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository )
        run: make publish-pact
      - if: github.event_name == 'push' || ( github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository )
        run: |
          make can-i-deploy || echo "::warning:: can-i-deploy says no; provider(s) must successfully verify before release"

  make-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
      - name: make build
        run: make build
