name: Generate Provenance
on:
  workflow_dispatch:

env:
  IMAGE_NAME: foo_name
  DIGEST: foo_digest

jobs:
  provenance:
    permissions:
      actions: read # for detecting the Github Actions environment.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
    # if: startsWith(github.ref, 'refs/tags/')
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.10.0
    with:
      image: $IMAGE_NAME
      digest: $DIGEST
    secrets:
      registry-username: ${{ secrets.DOCKERHUB_USER }}
      registry-password: ${{ secrets.DOCKERHUB_PASSWORD }}
