name: Generate Provenance
on:
  workflow_dispatch:

env:
  IMAGE_NAME: foo_name
  DIGEST: foo_digest

jobs:
  echo-vars:
    runs-on: ubuntu-latest
    steps:
    - name: echo vars
      shell: bash
      run: |
        echo "${{ env.IMAGE_NAME }} ${{ env.DIGEST }}."



  provenance:
    permissions:
      actions: read # for detecting the Github Actions environment.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
    if: startsWith(github.ref, 'refs/tags/')
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.10.0
    with:
      image: ${{ env.IMAGE_NAME }}
      digest: ${{ env.DIGEST }}
      registry-username: ${{ secrets.DOCKERHUB_USER }}
      registry-password: ${{ secrets.DOCKERHUB_PASSWORD }}
